<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="/inmydreams/dreams/style/style.css">
    <title>InMyDreams</title>
</head>
<body>

	<header>
		<nav>
			<?php require_once __DIR__ . '/../partials/nav.phtml'; ?>       
		</nav>
	</header>
	<main>
		<section class="section-a-propos">
			<h1 class="h1-a-propos">À propos de InMyDreams</h1>
				<p class="p1-a-propos">InMyDreams est un site de rencontre qui vous permet de partager vos rêves et de matcher avec d'autres utilisateurs selon la similitude 
            		de vos réponses. Nous avons également un chat pour dialoguer en direct et un QCM à remplir pour trouver le rêveur de vos rêves.</p>
				<p class="p2-a-propos">Sur InMyDreams, vous pouvez suivre vos rêves favoris, en ajouter un, rechercher des utilisateurs ou des rêves par mots clés, 
            		et bien plus encore.</p>
			<h2 class="h2-a-propos">Notre mission</h2>
				<p class="p3-a-propos">Notre mission est de créer une communauté de rêveurs qui partagent leurs expériences et leurs aspirations, 
            		et qui trouvent des personnes compatibles avec qui faire des rencontres significatives.</p>
			<h2 class="h2-a-propos">Contactez-nous</h2>
				<p class="p4-a-propos">Si vous avez des questions ou des commentaires sur InMyDreams, n'hésitez pas à nous contacter :</p>
		</section>
		</main>
	<footer>
		<?php require_once __DIR__ . '/../partials/footer.phtml'; ?>   
	</footer>	
</body>
</html>