<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="/inmydreams/dreams/style/style.css">
    <title>Inscription réussie</title>
  </head>

  <body>
    <header>
			  <nav>
            <?php require_once __DIR__ . '/../partials/nav.phtml'; ?>       
        </nav>
		</header>

  <main>
	  <h1>Inscription réussie</h1>
	  <p>Votre inscription a été enregistrée avec succès. Merci de votre inscription !</p>
  </main>

  </body>
</html>