

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css" crossorigin="anonymous">
	<link rel="stylesheet" href="/inmydreams/dreams/style/style.css">
	<title>Formulaire de connexion</title>
    </head>
<body>
	<header>
            <nav>
			    <?php require_once __DIR__ . '/../partials/nav.phtml'; ?>       
		    </nav>
		    <h1 class="form_co_h1">Formulaire de connexion</h1>
    </header>
	<main>
		<section class="form_connexion">
			<form class="form_co" action="" method="post">
				<div class="form_co_pseudo">
					<label class="form_co_label" for="pseudo">Pseudo :</label>
					<input  class="form_co_input" type="text" id="pseudo" name="pseudo">
				</div>
				<div class="form_co_mdp">
					<label class="form_co_label"for="mdp">Mot de passe :</label>
					<input class="form_co_input"  type="password" id="mdp" name="mdp">
				</div>
				<div>
					<button class="form_co_submit" type="submit">Connexion</button>
                	<button class="form_co_reset" type="reset">Réinitialiser</button>
				</div>
			</form>
		</section>
        <?=$message ?? '' ?>
	</main>
	<footer>
		<?php require_once __DIR__ . '/../partials/footer.phtml'; ?>   
	</footer>
</body>
</html>
