<?php

if (session_status() == PHP_SESSION_NONE) {
  session_start();
}

require_once __DIR__ . '/../dao/dao_Utilisateur.php';
$lesUtilisateurs = getAllUtilisateurs();
 ?>


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="/inmydreams/dreams/style/style.css">
    <title>InMyDreams</title>
  </head>
<body>  
    <header class="header-users">
        <nav>
            <?php require_once __DIR__ . '/../partials/nav.phtml'; ?>       
        </nav>     
        <h2 class="titre-utilisateur">Utilisateurs</h2>
    </header>
    <main class="main-users">
        <div class="cards-grid-users">
            <?php $i = 0; ?>
            <?php foreach ($lesUtilisateurs as $unUtilisateur): ?>
                <div class="card-users shadow-1" style="animation-delay: <?php echo ($i * 0.15); ?>s">
                    <h3 class="pseudo-utilisateur"><?= $unUtilisateur['pseudo'] ?></h3>
                    <p class="prenom-utilisateur"><?= $unUtilisateur['prenom'] ?></p>
                    <p class="dateNaissance-utilisateur"><?= $unUtilisateur['date_naissance'] ?></p>
                    <p class="descript-utilisateur"><?= $unUtilisateur['descript'] ?></p>
                    <a href="index.php?page=utilisateur&action=page-user&id_utilisateur=<?= $unUtilisateur['id_utilisateur'] ?>" class="bouton-psst">Psssst par ici</a>
                </div>
                <?php $i++; ?>
            <?php endforeach; ?>
        </div>
    </main>
    <footer class="footer-users">
        <?php require_once __DIR__ . '/../partials/footer.phtml'; ?>   
    </footer>
</body>
</html>
