<div class="footer-container">
  <div class="footer-contact">
    <h4>Contact</h4>
    <p>Adresse : 123 Dream St.</p>
    <p>Téléphone : (555) 555-5555</p>
    <p>Email : contact@partagedereves.com</p>
  </div>
  <div class="footer-links">
    <h4>Règles et conditions</h4>
    <ul>
      <li><a href="#">Règles du site</a></li>
      <li><a href="#">Conditions d'utilisation</a></li>
    </ul>
  </div>
  <div class="footer-socials">
    <h4>Réseaux sociaux</h4>
    <div class="footer-socials-logos">
      <a href="#" target="_blank" rel="noopener noreferrer"><i class="fab fa-facebook-square"></i></a>
      <a href="#" target="_blank" rel="noopener noreferrer"><i class="fab fa-instagram"></i></a>
      <a href="#" target="_blank" rel="noopener noreferrer"><i class="fab fa-twitter-square"></i></a>
    </div>
  </div>
  <div class="footer-legal">
    <ul>
      <li><a href="#">Mentions légales</a></li>
      <li><a href="#">Politique de protection des données</a></li>
    </ul>
  </div>
</div>




